### ISSUE TITLE
(10) As an instructor, I want to be able to look up questions stored in the application for my class so I can decide which ones to use.

### ISSUE THREAD

**Issue by kreatz-gatech** [jds2017/ALRails#13]
As an instructor, I want to be able to look up questions stored in the application for my class so I can decide which ones to use.

**Comment by jensptan** [comment]
Searching tags (user story 14)

**Comment by jensptan** [comment]
Not closing this yet. Need to add class names as tags upon question creation.

**Comment by jensptan** [comment]
Resolved when #88 was merged into master.
