### ISSUE TITLE
(5) As an instructor/TA, I want to be able to open and close questions to the class so that students can answer them.

### ISSUE THREAD

**Issue by kreatz-gatech** [jds2017/ALRails#8]
As an instructor/TA, I want to be able to open and close questions to the class so that students can answer them.

**Comment by jensptan** [comment]
Question has to be made visible (is it open right now?), students have to see presented/open questions across multiple machines.

**Comment by jensptan** [comment]
Rails may have some kind of functionality to assist with web sockets broadcasting/receiving. Estimate is made based on rails having this functionality.
